### ISSUE TITLE
لیست دستورات قابل استفاده

### ISSUE THREAD

**Issue by hamedefatian** [mmdchnar/marzban-telebot#5]
سلام
ممنون از ربات 
خیلی کارمون رو راه می اندازه
نیاز دارم بدونم چه دستوراتی رو میشه استفاده کرد
مثل start
مثل وقتی نام کاربر رو میدیم اطلاعاتش رو مینویسه
دستور قابل استفاده دیگه ای داره؟

**Comment by mmdchnar** [comment]
/start , /help
این دوتا یک کارو میکنن و فقط برای ادمین کار میکنه

/usage username
این برای همه کار میکنه و اطلاعات کاربری یوزر نیم رو نشون میده (بدون لینک ساب یا کانفیگ ها)

پیام عادی هم برای ادمین پنل یوزر رو میاره

همیناس فقط
